### ISSUE TITLE
403 error on "My Medical" when a non-admin user is assigned as a patient's legal rep

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#120]
When I assigned "YourCompany, Demo Portal User" to be the legal representative of a patient and then went to "My Medical" as the Portal User, I received a "403: Forbidden" error.

**Comment by woodbrettm** [comment]
@lasley adding the "medical user" rights to a user is marking them as an employee right? Not really sure whether that should be applied to the demo portal user or not, as I know you need at least that to view patients in website. Also looks like a bunch of medical rights were added to the non-portal demo user by default in 10.0 which is nice, woot!

On a side note. I'm puzzled that all the demo data patients have [MyCompany, Demo User] as their legal rep, but when creating a new patient, you can only select [MyCompany, Demo Portal User] or [Demo User, Emma Fields], for example. [MyCompany, Demo User] is not even an option.

@kellylougheed thanks for posting this issue! Been kinda thinking about this for awhile.

**Comment by lasley** [comment]
`portal` is a customer. Everyone else is an employee.

The issue here is that the data is being assigned to an employee and not a portal user. The security isn't setup for an employee to use My Medical.

I'll have to look at this one.

**Comment by woodbrettm** [comment]
@lasley I think according to [here](https://github.com/LasLabs/vertical-medical/blob/release/10.0/medical/views/medical_patient.xml#L51), this just infers if you have another patient as your legal rep right?

If so, I think I should remove all of the parent_id fields from patient demo data, and then populate res.users with the patients as well so we can log in as the patient to see their own prescription in website_portal.

Would that be a good idea?

**Comment by woodbrettm** [comment]
The `share` (Internal User) field would be set to False, and `is_customer` set to True in res.users demo.

**Comment by lasley** [comment]
Hmmmmm I don't know if I like the idea of adding more demo users into the mix. Maybe we should instead add a hook to update the users assigned to the demo employee to the demo portal user upon install (of website_portal_medical)

**Comment by woodbrettm** [comment]
Yeah that's a good idea. Do you think we should attach a medical_patient record to the portal user with some rxs as well? Just curious if we should have some demo to ensure a user can view their own prescriptions and such.

**Comment by woodbrettm** [comment]
and not just people they legally represent

**Comment by lasley** [comment]
Technically everything is setup so that a partner always represents a patient, if they are created through the front end. I'm good with adding a direct patient though too in order to cover someone doing it wrong.
