### ISSUE TITLE
sale_crm_medical_prescription: error when creating lead

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#138]
I got this error while creating a lead in sale_crm_medical_prescription:

File "/media/sf_vertical-medical/sale_crm_medical_prescription/wizards/medical_lead_wizard.py", line 78, in action_create_leads
    'name': ', '.join(l.name for l in order)
TypeError: sequence item 0: expected string, bool found

**Comment by woodbrettm** [comment]
This issue was fixed in oca/vertical-medical#164 :) however it seems the changes have not been ported yet to laslabs release/10.0.

**Comment by lasley** [comment]
Woot let's cherry pick those and knock this out!
