### ISSUE TITLE
website_sale_medical_medicament, website_sale_medical_medicament_us: error installing

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#142]
When I tried to separately install website_sale_medical_medicament and website_sale_medical_medicament_us, I got this error: KeyError: 'medicament_ids'

**Comment by lasley** [comment]
Missing depend

**Comment by kellylougheed** [comment]
@lasley After trying to recreate this error, I haven't encountered it again and have successfully installed both modules. Should I close the issue?
