### ISSUE TITLE
Errors installing medical_emr and medical_emr_data

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#143]
Even though these two modules have "installable: False," I still tested them.

I got this error when I tried to install medical_emr:

  File "/media/sf_vertical-medical/medical_emr/__init__.py", line 23, in <module>
    from . import models
  File "/media/sf_vertical-medical/medical_emr/models/__init__.py", line 23, in <module>
    from . import medical_pathology_category
ImportError: cannot import name medical_pathology_category

I got this error when I tried to install medical_emr_data:

  File "/opt/odoo/odoo/tools/misc.py", line 195, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/opt/odoo/odoo/tools/misc.py", line 242, in _fileopen
    raise IOError('File not found: %s' % basename)
IOError: File not found: medical_emr/views/medical_sequence.xml

**Comment by lasley** [comment]
Ahhh these are deprecated. They were basically super modules & have been stripped into something like 15 new modules. We're keeping them there though, because there's still some logic that hasn't been adapted & we don't want to lose.
