### ISSUE TITLE
medical_family: Error installing

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#144]
Even though medical_family has "installable: False," I tried to install it and got this error:

File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
Field `has_image` does not exist

Error context:
View `medical.patient.form`
[view_id: 357, xml_id: medical_family.medical_patient_view_form, model: medical.patient, parent_id: 353]

Error context:
View `medical.patient.form`
[view_id: 357, xml_id: medical_family.medical_patient_view_form, model: medical.patient, parent_id: 353]

**Comment by lasley** [comment]
Crap I forgot this module exists. We need to upgrade, I don't think it's gone to v9 or 10. Go ahead and perform a 1:1 migration for v9 & submit to OCA.

I'll take a look at the migration & get us a scope for a better v10 version. Dang I'm surprised nobody at SMD noticed this!
