### ISSUE TITLE
medical_operational: Error installing

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#145]
Even though medical_operational has "installable: False," I tried installing it and got this error:

  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
Field `has_image` does not exist

Error context:
View `medical.patient.form`
[view_id: 361, xml_id: medical_family.medical_patient_view_form, model: medical.patient, parent_id: 353]

Error context:
View `medical.patient.form`
[view_id: 361, xml_id: medical_family.medical_patient_view_form, model: medical.patient, parent_id: 353]

**Comment by lasley** [comment]
This is legacy & slated for upgrade. Good to close!
