### ISSUE TITLE
Website Portal Medical Patients Form Not Loading When Clicking on Patient

### ISSUE THREAD

**Issue by woodbrettm** [LasLabs/vertical-medical#165]
* [patient.website_url](https://github.com/LasLabs/vertical-medical/blob/release/10.0/website_portal_medical_patient/views/patients_template.xml#L22) is not returning an integer value. Only '#'.
* Because of the above point, when I click on a patient, it doesn't do anything
* Also should get rid of the patient name underline when clicking on the patient (it underlines just before redirecting to the patient form)

@LasLabs/admins as per the first point, could this be an issue in the controller, or is a different helper method being used in 10.0?

**Comment by lasley** [comment]
The issue is [here](https://github.com/LasLabs/vertical-medical/blob/release/10.0/website_portal_medical_patient/models/medical_patient.py#L19). I assume the operation of `'website.published.mixin'` changed

**Comment by woodbrettm** [comment]
Ah I see didn't notice that. Thanks for pointing it out!

**Comment by lasley** [comment]
Looks like it's untested too, so we should fix that at the same time to prevent future migration problems such as this

**Comment by lasley** [comment]
Note that there is also a broken JS asset link (look in assets.xml):
```
Could not get content for /website_medical/static/src/js/delete_form.js defined in bundle 'web.assets_frontend'.
(anonymous) @ web.assets_frontend.js:39

```
