### ISSUE TITLE
[RFC] Website Portal Medical Structure

### ISSUE THREAD

**Issue by woodbrettm** [LasLabs/vertical-medical#239]
@lasley @obulkin @hughesbm 

Hey guys,

Just posting this for the website portal medical redesign and wanted to gather your thoughts as I just finished some brainstorming.

I ended up with a lot of ideas, but did so in the hopes of exploring where we might put our current stuff (the prescriptions and patient info), and how to structure it.

The following headers are some ideas so far on different sections for the medical experience. Prescriptions would go under **Plans**, and the patient info would go under **Medical Info**.

# Sections
   
## Dashboard

- my/medical home page

## Medical Info

- **Conditions**
    - e.g. Diabetes
    - **Past Conditions**
        - e.g. Alcohol abuse or a disease, etc.
    - **Current Conditions**
        - e.g. Allergies, broken collar bone, etc.
        - State
            - Improving, etc.
    - **At-Risk Conditions**
        - Genetic
        - From health, environment, etc.
    - Notes

- **Immunizations**
    - Vaccination
    - Date vaccinated
    - Vaccinated where at what facility
    - Valid Until

- Height
- Weight
- Age
- Current Blood Test Data
    - Cholesterol, etc. What's important?
    - Blood Type

## Reports

- Labs results (blood test)
- Doctors can publish a variety of reports
    - Blood test
    - Disease results
    - Cancer results
    - Custom-built reports with custom fields
    - These are not PDF reports necessarily (although can be printed into pdf). For example when a blood test report is created, the user's blood data in their personal info page will auto update.
- Users can complete reports as well, for example a fitness or heartrate report, which can then be attached to plans.

## Calendar

- Appointments
    - Integration with google calendar, etc.
- Tasks (i.e. take 1 pill of advil, etc.)
    - Integration with certain personal task apps
- Can pull tasks from family members if given permissions. (great for parent managing things their child has to do)

## Documents

- Upload any documents here.
- This page also shows any document uploaded into the user's account.

## Purchases

- Invoices from prescriptions, etc.

## Inventory

- Tools such as Epipens, etc.
    - Expiration date

- List inventory of medicine and projected completion dates before needed refill
    - For example could list medications, and estimated available pills the customer has.
        - Perhaps can be edited by the user with approval from doctor
        - Maybe also have auto-refill orders

## Contacts

- Option to request to change doctor
- Option to request to get a new type of professional (for example you currently have a doctor but need an eye specialist)
- All medical contacts, with their type easily viewable (doctor, physician, etc.)
    - Each contact has an availability calendar
    - Users can start a chat thread with the doctor, etc.
    - User can schedule on-premise appointments or online video appointments
        - Urgency of appointment can be specified
- Family members and friends
    - Can give any of them access to one's own account
        - Perhaps have different permissions the user can set on those
            - Prescriptions
            - Certain Personal Info
            - Plans
            - Inventory
            - Purchases
            - Documents
            - Edit Calendar or Pull items from calendar

## Settings

-   Users who have access to my data
    - Permissions
- Notification Settings
- Import Data
- Integrations
- Profile Picture

## Plans

- Prescriptions
- Insurance
- Custom
    - Say a plan to eliminate a disease a user has, or deal with AIDS, etc.
    - Say a plan to reduce cholesterol.
        - Would consist of several milestones of cholesteral goals along a timeline, like a project.
        - Recommended dates to purchase stuff
        - Symptoms info
        - Fitness test results
        - Can also attach surgery calendar events, and set as a milestone

## Help Info

- Contact Info and locations, general support.
- Centralized page for where medical professionals post how-to stuff, link videos, etc.
- Case Scenarios will also be here
    -  For example, say when creating a medicament, a doctor can also specify the steps an individual should take if accidentally overdosing on something. The doctor can then attach this case scenario directly to the medicament. Thus, when a customer purchases that medicament, the case scenario will be both viewable here and also in context with the medicament, as well as in the plan views.

**Comment by lasley** [comment]
This is way beyond the scope of what your ticket calls for- please read the ticket requirements again. We simply want to look like the v10 My Account, using features we already have.

**Comment by woodbrettm** [comment]
Okie dokes sounds good.
