### ISSUE TITLE
External dependency undocumented

### ISSUE THREAD

**Issue by jcdrubay** [LasLabs/vertical-medical#76]
You try to install module 'website_sale_medical_prescription' that depends on module 'website_field_autocomplete_related'.
But the latter module is not available in your system.

I found it here: git@github.com:OCA/website.git

I guess this should be documented somewhere.

**Comment by jcdrubay** [comment]
Actually it is not in main 10.0 branch... waiting for https://github.com/OCA/website/pull/270

**Comment by lasley** [comment]
@jcdrubay Thanks for reporting. We do already have the branch in the oca_dependencies.txt, but I went ahead and added a note pointing to the PR for good measure: #86

**Comment by jcdrubay** [comment]
Thanks for answering and for the PR :) It's a pleasure working with you!
