### ISSUE TITLE
Errors when creating a prescription

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#90]
Could not add patient -- ValueError: Invalid field u'is_patient' in leaf "<osv.ExtendedLeaf: (u'is_patient', u'=', True) on medical_patient (ctx: )>"

Could not add doctor -- ValueError: Invalid field u'is_doctor' in leaf "<osv.ExtendedLeaf: (u'is_doctor', u'=', True) on medical_physician (ctx: )>"

Could not add pharmacy -- ValueError: Invalid field u'is_pharmacy' in leaf "<osv.ExtendedLeaf: (u'is_pharmacy', u'=', True) on medical_pharmacy (ctx: )>"

**Comment by jcdrubay** [comment]
I think this was fixed with #90 by yourself @kellylougheed  :+1:  Thanks

**Comment by lasley** [comment]
@jcdrubay #97 actually, but yup!

@kellylougheed - going forward, please try to manage the ticket associated with a PR in parallel. You can either do this by tagging the ticket in your comment, or even easier is to use your commit notes - https://help.github.com/articles/closing-issues-via-commit-messages/
