### ISSUE TITLE
Unclear mandatory fields for creating doctor & pharmacy

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#92]
When I was creating a new doctor & new pharmacy, it said that I had missed mandatory fields, but I couldn't tell which we were mandatory. Also, depending on the user, it might be helpful to have more guidance about what specific required ID numbers look like (number/type of characters, etc).

**Comment by lasley** [comment]
Any idea which fields were missed? The mandatory ones are denoted with purple highlight, but sometimes they are hidden in a notebook page that's not focused or something. I'm not seeing anything that immediately stands out though, but I'm probably blind to it.

Which ID numbers? Like DEA and NPI and stuff?

**Comment by kellylougheed** [comment]
Yeah, I specifically remember the DEA and NPI numbers. I didn't realize that the purple highlight meant mandatory! I'm used to the star beside the field, I guess. That makes more sense...

**Comment by lasley** [comment]
Alright we'll yield on the default thing, but do keep an eye out for ones that are obscured in notebook pages (those are the tab things you'll see all over). All required fields should be front-and center to the default view.

There's actually a module to add the star if you want it, that's just a UI thing. Ponder on that as you keep using the system - I personally think that no star looks a bit cleaner, but I'm rather plain 😛 

Sweet we'll add some help attrs to the US IDs then - I'll add to your board & you can learn all about them!
